codecov:
  require_ci_to_pass: true

coverage:
  status:
    project:
      default:
        # basic
        target: auto
        threshold: 5%
        base: auto
        # this is the advanced section
        if_not_found: success
        if_ci_failed: error
        informational: false
        only_pulls: true
    # below is patch level status
    patch:
      default:
        # basic
        target: 75%
        threshold: 10%
        base: auto
        # advanced
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error
        only_pulls: true
        informational: false

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false
