name: Test and Publish
on:
  push:
    branches: [main]
    paths-ignore:
      - '**/README.md'
      - '**/CODEOWNERS'
      - '**/.gitignore'
      - '**/codecov.yml'
  pull_request:

jobs:
  ###############################################
  # Run tests and publish coverage to codecov.io
  ###############################################
  test:
    runs-on: self-hosted
    env:
      base-directory: ./

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: "temurin"

      - name: Test
        run: ./gradlew test

      - name: codecov upload
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          file: ./lib/build/codecov/test/jacocoTestReport.xml

# TODO: disabling this until I figure out details
#  publish:
#    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
#    name: Publish library to Nexus
